baseURL: 'https://keloran.dev'
languageCode: 'en-us'
title: 'Keloran blog and random stuff'
theme: 'github-style'
copyright: 'Keloran'
enableEmoji: true
params:
  favicon: https://avatars.githubusercontent.com/u/200350?v=4
  github: Keloran
  url: https://keloran.dev
  rss: true
  avatar: https://avatars.githubusercontent.com/u/200350?v=4
  linkedin: keloran
  twitter: keloran
  description: |
    Keyboard builder, Golang developer
  github_accounts:
    - name: keloran
      image: https://avatars.githubusercontent.com/u/200350?v=4
    - name: bugfixes
      image: https://avatars.githubusercontent.com/u/7994911?s=64&v=4
    - name: chewedfeed
      image: https://avatars.githubusercontent.com/u/35765419?s=64&v=4
    - name: tracklines
      image: https://avatars.githubusercontent.com/u/28525656?s=64&v=4
    - name: nordicarts
      image: https://avatars.githubusercontent.com/u/8436400?s=64&v=4
    - name: fruitstall
      image: https://avatars.githubusercontent.com/u/51120162?s=64&v=4
    - name: todo-lists-app
      image: https://avatars.githubusercontent.com/u/107482119?s=64&v=4
    - name: k8sdeploy
      image: https://avatars.githubusercontent.com/u/93620800?s=64&v=4
    - name: retro-board
      image: https://avatars.githubusercontent.com/u/95586638?s=64&v=4
